### ISSUE TITLE
Does library need to be updated to use  MongoDB\Driver\Manager?

### ISSUE THREAD

**Issue by schmoove** [intekhabrizvi/Codeigniter-mongo-library#8]
Getting "The MongoDB PECL extension has not been installed or enabled", despite phpinfo reporting the extension being installed:

```
mongodb version: 1.1.7
```

If I try to initialize MongoClient I get:

```
Fatal error: Class 'MongoClient' not found 
```

But if I use the latest class syntax:

```
new MongoDB\Driver\Manager("mongodb://localhost:27017");
```

It works.

Is the library outdated?

**Comment by schmoove** [comment]
Ah I see, this is compatible with the legacy PECL "mongo" library at this point?

[http://php.net/manual/en/class.mongoclient.php](http://php.net/manual/en/class.mongoclient.php)

Happy to submit a PR for compatibility with the new "mongodb" library if you like?

**Comment by zeeshanyshaikh** [comment]
Can we get update for new mongodb driver? https://pecl.php.net/package/mongodb

**Comment by exblopz** [comment]
I've got error too. 

The MongoDB PECL extension has not been installed or enabled

Eventough I already installed this extension in my machine.

**Comment by pranavparulekar** [comment]
This library is outdated. It's not supporting to PHP >= 7.0 and mongo >= 3.0.

MongoClient Class is deprecated in PHP 7.xx because of PECL "mongo" package has been superseded.
Ref. links 
http://php.net/manual/en/class.mongoclient.php
https://pecl.php.net/package/mongo

Alternative class is MongoDB\Driver\Manager  
Ref. links
http://php.net/manual/en/set.mongodb.php
https://pecl.php.net/package/mongodb

If you installed MongoDB PECL extension successfully but still you are getting "The MongoDB PECL extension has not been installed or enabled", that means you had installed PECL "mongodb" package, not "mongo" package.

**Comment by zeeshanyshaikh** [comment]
Can you try this..
https://github.com/zeeshanyshaikh/Codeigniter-mongo-library
